apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-dns=allowed'
      to DNS running in 'kube-system'.

      In practice, most of the Pods which require network Egress need this label.
  name: allow-to-dns
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-dns: allowed
  egress:
  - to:
    {{- if .Values.nodeLocalDNSEnabled }}
    {{- if .Values.dnsServer }}
    - ipBlock:
        cidr: {{ .Values.dnsServer }}/32 # required for node local dns feature, allows egress traffic to kube-dns
    {{- end }}
    {{- if .Values.nodeLocalIPVSAddress }}
    - ipBlock:
        cidr: {{ .Values.nodeLocalIPVSAddress }}/32 # required for node local dns feature, allows egress traffic to node local dns cache
    {{- end }}
    {{- end }}
    - namespaceSelector:
        matchLabels:
          role: kube-system
      podSelector:
        matchExpressions:
        - {key: k8s-app, operator: In, values: [kube-dns,coredns]}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 8053
    - protocol: TCP
      port: 8053
  policyTypes:
  - Egress
  ingress: []
