apiVersion: {{ include "ingressversion" . }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: {{ .Chart.Name }}-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  tls:
  {{- range .Values.ingress.hosts }}
  - secretName: {{ required ".secretName is required" .secretName }}
    hosts:
    - {{ required ".hostName is required" .hostName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ required ".hostName is required" .hostName }}
    http:
      paths:
      - backend:
          {{- if semverCompare ">= 1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: alertmanager-client
            port:
              number: 9093
          {{- else }}
          serviceName: alertmanager-client
          servicePort: 9093
          {{- end }}
        path: /
        pathType: Prefix
  {{- end }}

