apiVersion: {{ include "daemonsetversion" . }}
kind: DaemonSet
metadata:
  labels:
    k8s-app: konnectivity-agent
    app: konnectivity-agent
    gardener.cloud/role: system-component
    origin: gardener
  namespace: kube-system
  name: konnectivity-agent
spec:
  selector:
    matchLabels:
      k8s-app: konnectivity-agent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        type: tunnel
        k8s-app: konnectivity-agent
        app: konnectivity-agent
        gardener.cloud/role: system-component
        origin: gardener
      annotations:
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      hostNetwork: true
      serviceAccountName: konnectivity-agent
      priorityClassName: system-cluster-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: konnectivity-agent
          image: {{ index .Values.images "konnectivity-agent" }}
          command:
            - /proxy-agent
          args:
            - --log-file=/var/log/konnectivity-agent/info.log
            - --logtostderr=false
            - --log-file-max-size=12
            - --ca-cert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - --proxy-server-host={{ .Values.proxyHost }}
            - --proxy-server-port=8132
            - --service-account-token-path=/var/run/secrets/tokens/konnectivity-agent-token
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
            {{- if .Values.global.vpaEnabled }}
              cpu: 400m
              memory: 400Mi
            {{- else }}
              cpu: "1"
              memory: 1Gi
            {{- end }}
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              port: 8093
              path: /healthz
            initialDelaySeconds: 15
            timeoutSeconds: 15
          volumeMounts:
            - name: konnectivity-agent-log
              mountPath: /var/log/konnectivity-agent
              readOnly: false
            - mountPath: /var/run/secrets/tokens
              name: konnectivity-agent-token
      volumes:
        - name: konnectivity-agent-log
          emptyDir: {}
        - name: konnectivity-agent-token
          projected:
            sources:
              - serviceAccountToken:
                  path: konnectivity-agent-token
                  audience: system:konnectivity-server
