apiVersion: {{ template "rbacversion" . }}
kind: ClusterRoleBinding
metadata:
  name: system:konnectivity-server
  labels:
    app: konnectivity-agent
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:konnectivity-server
