apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: gardener.cloud:psp:konnectivity-agent
  namespace: kube-system
  labels:
    app: konnectivity-agent
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:psp:kube-system:konnectivity-agent
subjects:
- kind: ServiceAccount
  name: konnectivity-agent
  namespace: kube-system
