apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-resource-manager
  namespace: {{ .Release.Namespace }}
  labels:
    gardener.cloud/role: controlplane
    app: gardener-resource-manager
